name: Release new docs

on:
  push:
    tags: [v*]
  release:
    types: [published]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ""
  ROBOT_NAME: ${{ github.actor }}
  ROBOT_EMAIL: ${{ github.actor }}@heathmont.net

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    outputs:
      image: ${{ steps.get_version.outputs.TAG_VERSION }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tag version
        id: get_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: heathmont/moon-react-docs:${{ steps.get_version.outputs.TAG_VERSION }}

  deployment:
    name: Update Docker Compose, Create Manifest, and Deploy
    runs-on: ubuntu-24.04
    needs: build-and-push
    steps:
      - name: Checkout Stacks Repo
        uses: actions/checkout@v4
        with:
          repository: coingaming/stacks
          token: ${{ secrets.GH_TOKEN }}
          ref: sportsbet-t2
          path: stacks

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare variables
        run: |
          echo "IMAGE=heathmont/moon-react-docs:${{ needs.build-and-push.outputs.image }}" >> $GITHUB_ENV

      - name: Check Image variable
        run: echo "IMAGE=${{env.IMAGE}}"

      - name: Update Docker Compose with New Image
        working-directory: stacks
        run: |
          yq -i '.services.moon-react-docs.image = "${{ env.IMAGE }}"' docker-compose.moon.yml

      - name: Commit and Push Changes to docker-compose file
        working-directory: stacks
        run: |
          git config user.email "${{ env.ROBOT_EMAIL }}"
          git config user.name "${{ env.ROBOT_NAME }}"
          git commit -am "Updated Docker image to ${{ env.IMAGE }}"
          git push origin sportsbet-t2
